### ISSUE TITLE
Bushes and grass on maintained road (W AIRPORT)

### ISSUE THREAD

**Issue by Walsh-UO** [WALancer/Rosche#11]
Not sure if this is intentional.  
https://steamuserimages-a.akamaihd.net/ugc/952961283030569007/BF60E3E6BD3025099ED7DA317C37CC12D1705896/

Located here
https://steamuserimages-a.akamaihd.net/ugc/952961283030569905/29A7B7C2084C1C89F3E725F75ABF2B70F9CE8C1F/

**Comment by Jayhag** [comment]
Possibly part of the forest layer on TB and not the xcam layer.
