### ISSUE TITLE
Missing Fence (Airport)

### ISSUE THREAD

**Issue by Walsh-UO** [WALancer/Rosche#12]
Not sure if this missing fence is intentional?
https://steamuserimages-a.akamaihd.net/ugc/952961283030579987/4339DD6B72A269A2F79815B1E0D46C01FBC1A6E0/

Located here
https://steamuserimages-a.akamaihd.net/ugc/952961283030580572/907573113D34F0F9AFAE83196FA199838429EC58/

**Comment by Jayhag** [comment]
AI cant navigate into the airport unless there are holes in the fences, If anything we need more holes.
The fence openings should be gates.

**Comment by WALancer** [comment]
need to put a broken fence there maybe?
