### ISSUE TITLE
Ramp issue (West side of Main river thing)

### ISSUE THREAD

**Issue by Walsh-UO** [WALancer/Rosche#14]
This ramp is not even
https://steamuserimages-a.akamaihd.net/ugc/952961283030616370/CB6DE0E9D65DD2C9E081921365E9228C3F504AE1/

Location
https://steamuserimages-a.akamaihd.net/ugc/952961283030617142/62959CCC4D04BCF05978C7E4CBE53E3814666300/

**Comment by Jayhag** [comment]
Already been fixed/removed.

**Comment by Jayhag** [comment]
@WALancer It would be nice if the terrain was slightly elevated so the ramp is functional.

**Comment by WALancer** [comment]
added different ramps
