### ISSUE TITLE
Bugged logs klein hesebeck

### ISSUE THREAD

**Issue by Jayhag** [WALancer/Rosche#203]
![image](https://user-images.githubusercontent.com/18515878/45912354-26223c00-bddd-11e8-859c-193ff55c8341.png)
![image](https://user-images.githubusercontent.com/18515878/45912355-2a4e5980-bddd-11e8-8b2a-dc51b8d066c9.png)

**Comment by WALancer** [comment]
I killed the one I know that glitches near there, Im going to wait and see if those logs are bugged out or not
