### ISSUE TITLE
Ground clipping / fucked terrain (weste)

### ISSUE THREAD

**Issue by Jayhag** [WALancer/Rosche#209]
![image](https://user-images.githubusercontent.com/18515878/45912430-4dc5d400-bdde-11e8-9530-7df7214eb189.png)
![image](https://user-images.githubusercontent.com/18515878/45912434-574f3c00-bdde-11e8-8cdb-28792f6091af.png)

**Comment by WALancer** [comment]
I love playing hide and seek.
