### ISSUE TITLE
Water is completely green when viewed from underwater

### ISSUE THREAD

**Issue by Freddo3000** [WALancer/Rosche#275]

**Comment by Jayhag** [comment]
I purposefully, made the water green due to the real life ponds and river water is a murky green.

**Comment by Freddo3000** [comment]
Fair enough, though in my opinion darkening it by a few shades wouldn't be too bad of an idea. Make of that what you will.

**Comment by Jayhag** [comment]
Yeah, Its a little tricky to mess with because you have to change a bunch of values in the config and pray that it looks right lol. But changing the color a bit is definitely something to look into in the future.
