### ISSUE TITLE
Dawn (sunrise) at 2:30 AM

### ISSUE THREAD

**Issue by eddb2020** [WALancer/Rosche#285]
Something seems to be wrong with the geo/time settings of the map, e.g. on 2018.06.21 dawn clocks in at 02:30 AM, at 03:00 I get almost full daylight. I think it should be still dark until 04 or 04:30 AM.
![2018-06-21 - 03 am](https://user-images.githubusercontent.com/46258585/50545770-aeee1680-0c1b-11e9-9e3c-ea15c8edaf30.jpg)

**Comment by eddb2020** [comment]
I've checked it with pure Vanilla and at 4 am on June 21 I get full daylight.

**Comment by WALancer** [comment]
As far as i know I've put the terrain in the correct position for arma's positioning system for its simulation of sunrise and sunset. I'm going to have to look into finding a better spot then..... yay arma....

**Comment by WALancer** [comment]
So I'm about to release an update for rosche, it is in the correct position.  I never thought about it before but, arma does not do daylights savings time. Thats why it seems so early.
