### ISSUE TITLE
Building clipping in barn (HANSTEDT)

### ISSUE THREAD

**Issue by Walsh-UO** [WALancer/Rosche#40]
This building next to barn is clipping into it
https://steamuserimages-a.akamaihd.net/ugc/952961283034441345/06AB2FE1A003D01984734AE2777D52A9A94863ED/

Location
https://steamuserimages-a.akamaihd.net/ugc/952961283034442016/631A18C15B6E1E60C8200944E04F0531613A7C14/

**Comment by WALancer** [comment]
This one is ok
