### ISSUE TITLE
Stupid Seesaw 01 (HALLIGDORF)

### ISSUE THREAD

**Issue by Walsh-UO** [WALancer/Rosche#9]
Stupid seesaw:

https://steamuserimages-a.akamaihd.net/ugc/952961283030542437/CA674933FD768A123B46B0EB815E9C1B36A23319/

Located here
https://steamuserimages-a.akamaihd.net/ugc/952961283030543159/F3188B69DD0586A4ED2CF23AF46726E48E13FDA7/

**Comment by Jayhag** [comment]
I put it there on purpose.

**Comment by Jayhag** [comment]
Stupid is a mean word @Walsh-UO =[
